title: Vivian Njibe
logo: MyImage.png
description: Data Anaylyst with 2 years of experience, manipulating and interrogating data, using anaytical tools such as Python, R, PowerBi, SQL and Advanced Excel.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
